// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Ban struct {
	ID       int32
	AdminID  int32
	Username string
	Ip       string
	Reason   pgtype.Text
	BannedAt pgtype.Timestamp
	ExpireAt pgtype.Timestamp
}

type Guild struct {
	ID          int32
	Name        string
	Tag         string
	LeaderID    pgtype.Int4
	Testimonial pgtype.Text
	Level       int32
	Exp         int32
	Points      int32
	Favors      int32
	IsActive    bool
	Color       int32
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type GuildBase struct {
	ID       int32
	GuildID  pgtype.Int4
	Name     string
	MinX     float32
	MinY     float32
	MaxX     float32
	MaxY     float32
	ExpireAt pgtype.Timestamp
}

type GuildCapturableZone struct {
	ID      int32
	Name    string
	GuildID pgtype.Int4
	MinX    float32
	MinY    float32
	MaxX    float32
	MaxY    float32
}

type GuildMember struct {
	ID       int32
	GuildID  int32
	PlayerID int32
	Role     int32
	Hour     int32
	Minute   int32
	Second   int32
}

type GuildPerk struct {
	ID      int32
	GuildID int32
	PerkID  int32
}

type Perk struct {
	ID          int32
	Name        string
	Description string
}

type Player struct {
	ID         int32
	Username   string
	Password   string
	Money      int32
	Level      int32
	Exp        int32
	Gold       int32
	Token      int32
	Hour       int32
	Minute     int32
	Second     int32
	Vip        int32
	Helper     int32
	IsOnline   bool
	Kills      int32
	Deaths     int32
	PosX       float32
	PosY       float32
	PosZ       float32
	PosAngle   float32
	Language   int32
	LastLogin  pgtype.Timestamp
	LastPlayed pgtype.Timestamp
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}

type Profit struct {
	ID          int32
	Name        string
	Description string
	Amount      int32
	ProfitType  int32
}

type ProfitableZone struct {
	ID       int32
	Name     string
	ProfitID pgtype.Int4
	MinX     float32
	MinY     float32
	MaxX     float32
	MaxY     float32
}

type Skin struct {
	ID       int32
	PlayerID int32
	SkinID   int32
	Active   bool
}
