// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type Ban struct {
	ID       int32
	AdminID  sql.NullInt32
	Username string
	Ip       string
	Reason   sql.NullString
	BannedAt sql.NullTime
	ExpireAt sql.NullTime
}

type Company struct {
	ID          int32
	Name        string
	Tag         string
	Description sql.NullString
	Balance     sql.NullInt32
	Multiplier  sql.NullFloat64
}

type CompanyApplication struct {
	ID          int32
	PlayerID    int32
	CompanyID   int32
	Description sql.NullString
	Accepted    int16
	CreatedAt   sql.NullTime
	ExpiredAt   sql.NullTime
	AnsweredAt  sql.NullTime
}

type CompanyMember struct {
	ID        int32
	PlayerID  int32
	CompanyID int32
	Role      int16
}

type CompanyMemberInfo struct {
	ID        int32
	PlayerID  int32
	CompanyID int32
	Hour      int32
	Minute    int16
	Second    int16
	Score     int32
	Level     int32
}

type Player struct {
	ID         int32
	Username   string
	Password   string
	Money      int32
	Level      int32
	Exp        int32
	Gold       int32
	Token      int32
	Hour       int32
	Minute     int32
	Second     int32
	Vip        int32
	Helper     int32
	IsOnline   bool
	Kills      int32
	Deaths     int32
	PosX       float32
	PosY       float32
	PosZ       float32
	PosAngle   float32
	Language   int32
	LastLogin  sql.NullTime
	LastPlayed sql.NullTime
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

type Skin struct {
	ID       int32
	PlayerID int32
	SkinID   int32
	Active   bool
}
