// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type Ban struct {
	ID       int32
	AdminID  int32
	Username string
	Ip       string
	Reason   sql.NullString
	BannedAt sql.NullTime
	ExpireAt sql.NullTime
}

type Guild struct {
	ID          int32
	Name        string
	Tag         string
	LeaderID    sql.NullInt32
	Testimonial sql.NullString
	Level       int32
	Exp         int32
	Points      int32
	Favors      int32
	IsActive    bool
	Color       int32
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type GuildBase struct {
	ID       int32
	GuildID  sql.NullInt32
	Name     string
	MinX     float32
	MinY     float32
	MaxX     float32
	MaxY     float32
	ExpireAt sql.NullTime
}

type GuildCapturableZone struct {
	ID      int32
	Name    string
	GuildID sql.NullInt32
	MinX    float32
	MinY    float32
	MaxX    float32
	MaxY    float32
}

type GuildMember struct {
	ID       int32
	GuildID  int32
	PlayerID int32
	Role     int32
	Hour     int32
	Minute   int32
	Second   int32
}

type GuildPerk struct {
	ID      int32
	GuildID int32
	PerkID  int32
}

type Perk struct {
	ID          int32
	Name        string
	Description string
}

type Player struct {
	ID         int32
	Username   string
	Password   string
	Money      int32
	Level      int32
	Exp        int32
	Gold       int32
	Token      int32
	Hour       int32
	Minute     int32
	Second     int32
	Vip        int32
	Helper     int32
	IsOnline   bool
	Kills      int32
	Deaths     int32
	PosX       float32
	PosY       float32
	PosZ       float32
	PosAngle   float32
	Language   int32
	LastLogin  sql.NullTime
	LastPlayed sql.NullTime
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

type Profit struct {
	ID          int32
	Name        string
	Description string
	Amount      int32
	ProfitType  int32
}

type ProfitableZone struct {
	ID       int32
	Name     string
	ProfitID sql.NullInt32
	MinX     float32
	MinY     float32
	MaxX     float32
	MaxY     float32
}

type Skin struct {
	ID       int32
	PlayerID int32
	SkinID   int32
	Active   bool
}
